# -*- coding: utf-8 -*-
"""aula1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17NBRQwOZiA9xW0yQOOR8NGFE069cuqQg
"""

#comentário de uma linha Python
#Conceito 1: Algoritmo é uma sequencia de passos para alcançar um fim.
#Maria precisa calcular o valor total de  melancias que ela comprou.
"""
Passo 1 - Perguntar quantas melancias? ok
Passo 2 - Guardar o valor da quantidade de melancia - 3 ok
Passo 3 - Perguntar o valor unitário da melancia ok
Passo 4 - Armazenar o valor unitário da melancia ok
Passo 5 - Realizar o cálculo do valor total ( 5 x 5 = 25)
Passo 6 - Mostrar o valor total
"""
"""
  comentário de múltiplas linhas Python
"""
#Passo 1 - Perguntar quantas melancias?
#print("Quantas melancias você quer comprar?")
#parte 1 - Entrada de Dados
qtde_produto = int(input("Quantas melancias você quer comprar?"))
print(type(qtde_produto))
valor_produto = float(input("Qual o valor unitário da melância?"))
print(type(valor_produto)) #snake_case
#parte 2 - Cálculo
valor_total = qtde_produto * valor_produto
#parte 3 - Mostrar
print(f"O valor total é:{valor_total} - pode efetuar o pagamento")